- src/main/java/YUNS_Backend/YUNS/config/SecurityConfig.java
- src/main/java/YUNS_Backend/YUNS/controller/UserController.java
- src/main/java/YUNS_Backend/YUNS/custom/CustomAuthenticationSuccessHandler.java
- src/main/java/YUNS_Backend/YUNS/custom/CustomUserDetails.java
- src/main/java/YUNS_Backend/YUNS/custom/LoginAuthenticationFilter.java
- src/main/java/YUNS_Backend/YUNS/entity/User.java
- src/main/java/YUNS_Backend/YUNS/service/UserService.java
로그인 기능 구현하고 User.createUser()에서 비밀번호 인코딩 후 DB에 저장하도록 수정했습니다!
> feature/userLogin: 로그인 기능 추가 및 회원가입 시 비밀번호 인코딩 과정 추가

- src/main/java/YUNS_Backend/YUNS/config/SecurityConfig.java
- src/main/java/YUNS_Backend/YUNS/controller/NoticeController.java
- src/main/java/YUNS_Backend/YUNS/dto/NoticeDto.java
- src/main/java/YUNS_Backend/YUNS/entity/Notice.java
- src/main/java/YUNS_Backend/YUNS/repository/NoticeRepository.java
- src/main/java/YUNS_Backend/YUNS/service/NoticeService.java
- src/main/java/YUNS_Backend/YUNS/service/UserService.java
> Feature/notices : 공지사항 기능 추가

- README.md
- build.gradle
- src/main/java/YUNS_Backend/YUNS/config/S3Config.java
- src/main/java/YUNS_Backend/YUNS/controller/QuestionController.java
- src/main/java/YUNS_Backend/YUNS/dto/QuestionDto.java
- src/main/java/YUNS_Backend/YUNS/entity/Question.java
- src/main/java/YUNS_Backend/YUNS/repository/QuestionRepository.java
- src/main/java/YUNS_Backend/YUNS/service/QuestionService.java
- src/main/java/YUNS_Backend/YUNS/service/S3Service.java
feature/questions: 1:1 문의 기능 구현 했습니다.
- 1:1문의 리스트 조회
- 1:1문의 세부 조회
- 1:1문의 글 작성
- 1:1문의 글 수정
- 1:1문의 글 삭제
> feature/questions: 1:1 문의 기능 구현

- src/main/java/YUNS_Backend/YUNS/config/SecurityConfig.java
- src/main/java/YUNS_Backend/YUNS/controller/UserController.java
- src/main/java/YUNS_Backend/YUNS/custom/CustomLogoutSuccessHandler.java
- src/main/java/YUNS_Backend/YUNS/dto/UserRegisterDto.java
- src/main/java/YUNS_Backend/YUNS/repository/UserRepository.java
- src/main/java/YUNS_Backend/YUNS/service/UserService.java
로그아웃, 회원탈퇴 기능 구현하고 loginTest api 삭제했습니다!
> feature/unRegister : 로그아웃, 회원탈퇴 기능 구현

- src/main/java/YUNS_Backend/YUNS/controller/QuestionController.java
- src/main/java/YUNS_Backend/YUNS/entity/Question.java
- src/main/java/YUNS_Backend/YUNS/service/QuestionService.java
> feature/questions : 마이페이지 내 1:1 문의 조회 기능 구현

- src/main/java/YUNS_Backend/YUNS/controller/QuestionController.java
- src/main/java/YUNS_Backend/YUNS/service/QuestionService.java
feature/userquestions: 1:1 문의 답변 기능 구현했습니다.
기존에는 해당 글 작성자만 글 수정, 삭제가 가능했는데
관리자도 가능하도록 수정했습니다.
> 1:1 문의 답변 기능 구현

- src/main/java/YUNS_Backend/YUNS/controller/NotebookController.java
- src/main/java/YUNS_Backend/YUNS/controller/UserController.java
- src/main/java/YUNS_Backend/YUNS/dto/NotebookDto.java
- src/main/java/YUNS_Backend/YUNS/entity/Notebook.java
- src/main/java/YUNS_Backend/YUNS/repository/NotebookRepository.java
- src/main/java/YUNS_Backend/YUNS/repository/UserRepository.java
- src/main/java/YUNS_Backend/YUNS/service/NotebookService.java
노트북 정보 등록 api 구현하고 자잘한 수정 했습니다
> Feature/notebooks: 노트북 정보 등록 기능 구현

- src/main/java/YUNS_Backend/YUNS/controller/NotebookController.java
- src/main/java/YUNS_Backend/YUNS/custom/CustomAuthenticationSuccessHandler.java
- src/main/java/YUNS_Backend/YUNS/custom/LoginAuthenticationFilter.java
- src/main/java/YUNS_Backend/YUNS/entity/Notebook.java
- src/main/java/YUNS_Backend/YUNS/repository/NotebookRepository.java
- src/main/java/YUNS_Backend/YUNS/service/NotebookService.java
노트북 정보 수정, 노트북 정보 삭제 기능을 구현하고 로그인 기능의 반환 값을 수정했습니다.
> feature/notebooks: 노트북 정보 수정, 노트북 정보 삭제 기능 구현

- src/main/java/YUNS_Backend/YUNS/controller/NoticeController.java
- src/main/java/YUNS_Backend/YUNS/service/NoticeService.java
> Feature/notices : paging 기능 추가

- src/main/java/YUNS_Backend/YUNS/controller/NotebookController.java
- src/main/java/YUNS_Backend/YUNS/controller/ReservationController.java
- src/main/java/YUNS_Backend/YUNS/controller/UserController.java
- src/main/java/YUNS_Backend/YUNS/dto/NotebookDetailDto.java
- src/main/java/YUNS_Backend/YUNS/dto/NotebookRegistRequestDto.java
- src/main/java/YUNS_Backend/YUNS/dto/UserRegisterDto.java
- src/main/java/YUNS_Backend/YUNS/entity/Notebook.java
- src/main/java/YUNS_Backend/YUNS/entity/Rental.java
- src/main/java/YUNS_Backend/YUNS/entity/Reservation.java
- src/main/java/YUNS_Backend/YUNS/entity/Type.java
- src/main/java/YUNS_Backend/YUNS/exception/CustomException.java
- src/main/java/YUNS_Backend/YUNS/exception/ErrorCode.java
- src/main/java/YUNS_Backend/YUNS/exception/ErrorResponse.java
- src/main/java/YUNS_Backend/YUNS/exception/GlobalExceptionHandler.java
- src/main/java/YUNS_Backend/YUNS/repository/RentalRepository.java
- src/main/java/YUNS_Backend/YUNS/repository/ReservationRepository.java
- src/main/java/YUNS_Backend/YUNS/service/NotebookService.java
- src/main/java/YUNS_Backend/YUNS/service/ReservationService.java
- src/main/java/YUNS_Backend/YUNS/service/UserService.java
커스텀에러, 노트북 상세 조회, 노트북 대여/연장 신청 구현했습니다
> feature/notebooks: 커스텀에러, 노트북 상세 조회, 노트북 대여/연장 신청 구현

- src/main/java/YUNS_Backend/YUNS/controller/RentalController.java
- src/main/java/YUNS_Backend/YUNS/dto/RentalDto.java
- src/main/java/YUNS_Backend/YUNS/dto/ReservationDto.java
- src/main/java/YUNS_Backend/YUNS/entity/Notebook.java
- src/main/java/YUNS_Backend/YUNS/entity/User.java
- src/main/java/YUNS_Backend/YUNS/service/QuestionService.java
- src/main/java/YUNS_Backend/YUNS/service/RentalService.java
> feature/rentalRequest: 대여요청 조회, 대여요청 승인 구현

- src/main/java/YUNS_Backend/YUNS/controller/ExtendController.java
- src/main/java/YUNS_Backend/YUNS/service/RentalService.java
> feature/extendRequest: 연장요청 조회, 연장요청 승인 구현

- src/main/java/YUNS_Backend/YUNS/controller/QuestionController.java
- src/main/java/YUNS_Backend/YUNS/service/QuestionService.java
> Feature/questions 1:1문의 리스트 조회 수정

- src/main/java/YUNS_Backend/YUNS/config/SecurityConfig.java
- src/main/java/YUNS_Backend/YUNS/controller/NotebookController.java
- src/main/java/YUNS_Backend/YUNS/custom/CustomAccessDeniedHandler.java
- src/main/java/YUNS_Backend/YUNS/custom/CustomAuthenticationEntryPoint.java
- src/main/java/YUNS_Backend/YUNS/dto/NotebookDetailDto.java
- src/main/java/YUNS_Backend/YUNS/dto/NotebookFilterDto.java
- src/main/java/YUNS_Backend/YUNS/dto/NotebookRegistRequestDto.java
- src/main/java/YUNS_Backend/YUNS/entity/Notebook.java
- src/main/java/YUNS_Backend/YUNS/exception/ErrorCode.java
- src/main/java/YUNS_Backend/YUNS/repository/NotebookRepositoryCustomImpl.java
노트북 등록 request dto 검증 추가 및 자잘한 수정
> Feature/notebooks: 노트북 등록 request dto 검증 추가 및 자잘한 수정

- src/main/java/YUNS_Backend/YUNS/config/SecurityConfig.java
- src/main/java/YUNS_Backend/YUNS/custom/CustomAuthenticationFailureHandler.java
- src/main/java/YUNS_Backend/YUNS/custom/CustomAuthenticationSuccessHandler.java
- src/main/java/YUNS_Backend/YUNS/dto/NotebookListDto.java
- src/main/java/YUNS_Backend/YUNS/exception/ErrorCode.java
- src/main/java/YUNS_Backend/YUNS/repository/NotebookRepositoryCustomImpl.java
- src/main/java/YUNS_Backend/YUNS/service/ReservationService.java
로그인 성공/실패 반환에 커스텀에러 적용하고 노트북 조회 반환에 OS 정보 추가했습니다!
> feature/notebooks : 로그인 성공/실패 반환 수정 및 노트북 조회 반환 수정

- src/main/java/YUNS_Backend/YUNS/dto/RentalDto.java
- src/main/java/YUNS_Backend/YUNS/entity/Rental.java
- src/main/java/YUNS_Backend/YUNS/service/RentalService.java
feat : 대여현환 조회 RentalStauts 추가 및 대여 현환 수정 코드 개선
> feat : 대여현환 조회 RentalStauts 추가 및 대여 현환 수정 코드 개선

- src/main/java/YUNS_Backend/YUNS/controller/QuestionController.java
> feat: 1:1문의 api 양식수정

- src/main/java/YUNS_Backend/YUNS/service/S3Service.java
> feat: AWS S3 버킷 변경

- src/main/java/YUNS_Backend/YUNS/controller/QuestionController.java
- src/main/java/YUNS_Backend/YUNS/dto/QuestionDto.java
- src/main/java/YUNS_Backend/YUNS/entity/Question.java
- src/main/java/YUNS_Backend/YUNS/service/QuestionService.java
feat: 1대1 문의 S3 이미지 여러개 업로드 기능 수정
> feat: 1대1 문의 S3 이미지 여러개 업로드 기능 수정

- src/main/java/YUNS_Backend/YUNS/controller/RentalController.java
- src/main/java/YUNS_Backend/YUNS/repository/ReservationRepository.java
- src/main/java/YUNS_Backend/YUNS/service/RentalService.java
> feat: rental lazy 수정

- src/main/java/YUNS_Backend/YUNS/controller/ExtendController.java
- src/main/java/YUNS_Backend/YUNS/dto/ReservationDto.java
- src/main/java/YUNS_Backend/YUNS/service/RentalService.java
feat: extend lazy 수정 및 대여요청 조회 필드 추가
> feat: extend lazy 수정 및 대여요청 조회 필드 추가

- src/main/java/YUNS_Backend/YUNS/controller/NoticeController.java
> feat: 공지사항 리스트 조회 정렬 기능 추가

- src/main/java/YUNS_Backend/YUNS/controller/ExtendController.java
> feat: extend 요청 조회 필드추가

- src/main/java/YUNS_Backend/YUNS/service/RentalService.java
feat: extend 승인 시 RENTAL 상태로 설정
> feat: extend 승인 시 RENTAL 상태로 설정

- src/main/java/YUNS_Backend/YUNS/controller/NoticeController.java
- src/main/java/YUNS_Backend/YUNS/repository/NoticeRepository.java
- src/main/java/YUNS_Backend/YUNS/service/NoticeService.java
> fix: 공지사항 500 error 수정
